apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: ecommerce
  labels:
    app: postgresql
    component: database
type: Opaque
data:
  username: YWRtaW4=          # echo -n 'admin' | base64
  
  # 添加 Pod 需要的 password 键
  password: cG9zdGdyZXMxMjM=  # echo -n 'postgres123' | base64
  postgres-password: cG9zdGdyZXMxMjM=
  postgres-root-password: cG9zdGdyZXMxMjM=
  postgres-replication-password: cG9zdGdyZXMxMjM=