apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: ecommerce
  labels:
    app: mongodb
    component: database
type: Opaque
data:
  username: YWRtaW4=          # echo -n 'admin' | base64
  password: bW9uZ29kYjEyMw==  # echo -n 'mongodb123' | base64
